name: RunicAchievements
version: '${project.version}'
main: com.runicrealms.plugin.RunicAchievements
api-version: 1.16
depend: [ RunicCore, RunicDatabase, RunicCommon ]
softdepend: [ RunicGuilds, RunicItems, RunicProfessions ]
authors: [ Skyfallin ]
