name: RunicAchievements
version: '${project.version}'
main: com.runicrealms.plugin.achievements.RunicAchievements
api-version: 1.16
depend:
  - RunicCore
  - RunicDatabase
  - RunicCommon
  - RunicGuilds
  - RunicItems
  - RunicProfessions
  - MythicMobs
  - WorldGuard
authors: [ Skyfallin ]
